Fix failing test when running from a short path
When running tests from a relatively short path, for example /tmp/a, it fails

    Failed tests:
      SoftAssertionsTest.should_be_able_to_catch_exceptions_thrown_by_all_proxied_methods:163
    Expecting:
     <"expected:</private/tmp/a/[b]> but was:</private/tmp/a/[a]>">
    to contain:
     <["expected:<...", "[b]> but was:<...", "[a]>"]>
    but could not find:
     <["expected:<...", "[b]> but was:<..."]>

I have override the error message with a static one to not depends on the way it is
dynamically built.